spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_management?currentSchema=main
    username: postgres
    password: 997764
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  messages:
    always-use-message-format: true
server:
  port: 9090